### PR TITLE
Tumblr Support

### PR DESCRIPTION
**Pull request by ghost**
I've added a Tumblr medium. It's on it's own branch 'tumblr'.
Stupidly I merged with master so your getting a bunch of other commits :(

### CODE REVIEW

**Comment by marcinbunsch** [comment]
Thanks a lot for this - any chance that you could add a spec so that we have regression testing? 

Also I noticed that you have a APIException - where is it coming from? I don't see it defined anywhere.

**Comment by ghost** [comment]
> Thanks a lot for this - any chance that you could add a spec so that we have regression testing?

I looked into doing that but there isn't anything to test unless I deliberately complicate the code. The other Medium specs have a lot of tests for config stuff which really should be 'dry'ed up and put in a config spec. That just leaves the post. There isn't much point in testing Net/Http. If you really want a spec then I guess I could try mocking out Net/Http...

> Also I noticed that you have a APIException - where is it coming from? I don't see it defined anywhere.

Sorry, my bad. This code is from a Tumblr API wrapper I wrote. The APIException is from there. I'll remove it and send you a new pull request.

Henry

**Comment by marcinbunsch** [comment]
Ok, great - so should I close this pull request and wait for a new one?

**Comment by ghost** [comment]
Yep.

**Comment by ghost** [comment]
I've fixed my Tumblr Medium code. You can either pull now or close this and I'll send another request.

**Comment by marcinbunsch** [comment]
Hi

I've been playing around with the Tumblr idea, it seems Tumblr now has an Oauth based API, so the current implementation is based on OAuth. Sorry it took so long :)

**Pull request closed without merging**
